### ISSUE TITLE
Ipopt requirements

### ISSUE THREAD

**Issue by blegat** [oxfordcontrol/SwitchTimeOpt.jl#1]
I have started [the SwitchedSystems.jl package](https://github.com/blegat/SwitchedSystems.jl) for Switched Systems in Julia.
The package is not planned to be specific to any algorithm but rather give a common interface for different algorithms.
Therefore, it seems to make sense to add SwitchTimeOpt as a option for design switching control.
I am still unsure how to do this between:
* SwitchedSystems.jl define a interface and SwitchTimeOpt.jl adds SwitchedSystems.jl in its REQUIRE file and implements the interface (a bit like what MathProgBase does).
* SwitchedSystems.jl adds SwitchTimeOpt.jl in its REQUIRE file and use it directly.

In the second option, this would mean that Ipopt becomes an indirect requirement for SwitchedSystems.jl. This is not a big issue but it is a bit annoying. Would it be possible to remove it from the REQUIRE file and select your default solver using [this method](https://github.com/JuliaOpt/MathProgBase.jl/blob/master/src/defaultsolvers.jl) ?

**Comment by bstellato** [comment]
Thank you for the interest in the package. It is a great idea to have a general Switched Systems package in Julia!

I think the second option could be the cleanest. I have updated SwitchTimeOpt removing the Ipopt requirement so that it uses the MathProgBase.defaultNLPsolver

The new METADATA.jl pull request is here: https://github.com/JuliaLang/METADATA.jl/pull/7214

Let me know if there are any other compatibility issues or problems with the package.

**Comment by blegat** [comment]
Thanks a lot !
